-- Calculates total product revenue generated by each customer

-- Revenue is defined as the sum of product prices, excluding shipping costs
SELECT c.customer_id, SUM(oi.price) AS prod_revenue FROM customers c
JOIN orders o ON c.customer_id = o.customer_id 
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id ORDER BY prod_revenue DESC 
LIMIT 10;

-- Revenue including freight 
SELECT c.customer_id, SUM(oi.price + oi.freight_value) AS prod_revenue_f FROM customers c
JOIN orders o ON c.customer_id = o.customer_id 
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id ORDER BY prod_revenue_f DESC 
LIMIT 10;
