-- Calculates the revenue generated by each seller in each product category and selects the maximum revenue per category, along with the 
-- corresponding seller ID. -- 

WITH seller_category_revenue AS (
    SELECT 
        t.product_category_name_english AS category,
        oi.seller_id,
        SUM(oi.price) AS total_revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    JOIN translation t ON p.product_category_name = t.product_category_name
    GROUP BY t.product_category_name_english, oi.seller_id
)
SELECT 
    category,
    seller_id,
    total_revenue
FROM seller_category_revenue s1
WHERE total_revenue = (
    SELECT MAX(s2.total_revenue)
    FROM seller_category_revenue s2
    WHERE s2.category = s1.category
)
ORDER BY category;