-- Calculates the revenue generated by each seller in each product category and selects the maximum revenue per category, along with the 
-- corresponding seller ID and it's % of market share for their corresponding category. --

WITH seller_category_revenue AS (
    SELECT 
        t.product_category_name_english AS category,
        oi.seller_id,
        SUM(oi.price) AS seller_revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    JOIN translation t ON p.product_category_name = t.product_category_name
    GROUP BY t.product_category_name_english, oi.seller_id
),
category_total_revenue AS (
    SELECT 
        category,
        SUM(seller_revenue) AS total_category_revenue
    FROM seller_category_revenue
    GROUP BY category
)
SELECT
    scr.category,
    scr.seller_id,
    scr.seller_revenue,
    ctr.total_category_revenue,
    ROUND(100.0 * scr.seller_revenue / ctr.total_category_revenue, 2) AS seller_pct_of_category
FROM seller_category_revenue scr
JOIN category_total_revenue ctr ON scr.category = ctr.category
WHERE scr.seller_revenue = (
    SELECT MAX(s2.seller_revenue)
    FROM seller_category_revenue s2
    WHERE s2.category = scr.category
)
ORDER BY seller_pct_of_category DESC;